---
apiVersion: v1
kind: Pod
metadata:
  name: books-api
  labels:
    app: books-api
spec:
  containers:
    - name: books-api
      image: askewseth/books-api
      ports:
        - containerPort: 5555
